name: CI

on:
  push:
  pull_request:
  schedule:
    - cron: '42 5 * * *'
  workflow_dispatch:

jobs:
  build-in-container:
    runs-on: ubuntu-latest
    container:
      image: python:3.7
    name: Run
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
            pip install -r requirements.txt
      - name: Monitor
        run: |
            python monitor.py config/*.json
